### ISSUE TITLE
纯技术网站被封就是你这样的自以为聪明自以为好玩的人太多导致的

### ISSUE THREAD

**Issue by ares89** [mlouielu/cn_constitution_2018#2]
纯技术网站被封就是你这样的自以为聪明自以为好玩的人太多导致的

**Comment by mlouielu** [comment]
喔是喔，我剛剛測試 GFW 沒封鎖啊，還是中國沒這種肚量，連字串比較都不能用 ^_^

**Comment by mlouielu** [comment]
@ares89 https://github.com/programthink/zhao 這個你看了估計又要吐血了吧？

**Comment by ares89** [comment]
要么你上街改变这种情况 要么就别出声
别在这影响只想安安静静的用github的同学们

**Comment by mlouielu** [comment]
根据相关法律法规和政策，搜索结果未予显示。
